AWSTemplateFormatVersion: "2010-09-09"
Description: This CloudFormation stack provisions and manages resources for domain registration using Amazon Route 53, and for the provisioning, validation, and management of SSL/TLS certificates using AWS Certificate Manager (ACM).

Parameters:
  HostedZoneId:
    Type: String
    Description: The Route 53 Hosted Zone ID for app-lift.com.
  AppFQDN:
    Type: String
    Description: The fully qualified domain name for the application.
  ALBStackName:
    Type: String
    Description: Name of the stack that manages ALB

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: app-lift.com
      DomainValidationOptions:
        - DomainName: app-lift.com
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
  ApplicationAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref AppFQDN
      Type: A
      AliasTarget:
        DNSName: !ImportValue
          Fn::Sub: "${ALBStackName}-PublicALBDNSName"
        HostedZoneId: !ImportValue
          Fn::Sub: "${ALBStackName}-PublicALBCanonicalHostedZoneId"
        EvaluateTargetHealth: true

Outputs:
  CertificateArn:
    Description: "ARN of the ACM certificate for app-lift.com"
    Value: !Ref Certificate
    Export:
      Name: !Sub "${AWS::StackName}-CertificateArn-AppLiftCom"
