AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Sets up core IAM resources for GitHub Actions OIDC deployments.
  Creates an IAM Role assumable by trusted GitHub Actions workflows via the OIDC provider.
  Also creates a reusable IAM Managed Policy (CloudFormationStackManagementPolicy) granting permissions to manage CloudFormation stacks.

Parameters:
  AWSAccountID:
    Type: String
    Description: "The 12-digit AWS Account ID"
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: "Must be a 12-digit AWS account ID."

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: "https://token.actions.githubusercontent.com"
      ClientIdList:
        - "sts.amazonaws.com"
      ThumbprintList:
        - "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  CloudFormationStackManagementPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CloudFormationStackManagementPolicy
      Description: Grants permissions to manage CloudFormation stacks (create, update, delete, describe, etc.)
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "cloudformation:CreateChangeSet"
              - "cloudformation:DeleteChangeSet"
              - "cloudformation:DescribeChangeSet"
              - "cloudformation:ExecuteChangeSet"
              - "cloudformation:CreateStack"
              - "cloudformation:UpdateStack"
              - "cloudformation:DeleteStack"
              - "cloudformation:DescribeStacks"
              - "cloudformation:DescribeStackEvents"
              - "cloudformation:DescribeStackResources"
              - "cloudformation:DescribeStackDriftDetectionStatus"
              - "cloudformation:GetTemplate"
              - "cloudformation:GetTemplateSummary"
              - "cloudformation:ListStackResources"
            Resource: "*"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W13
            reason: "This policy grants broad permissions for CloudFormation actions (cloudformation:*). Restricting the Resource scope to specific CloudFormation stack ARNs is impractical, as the role using this policy needs to manage diverse stacks throughout their lifecycle (create, update, delete)."
          - id: W28
            reason: "A fixed name is preferred for this common managed policy for easier identification."
  IamRoleStackDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IamRoleStackDeploymentRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWSAccountID}:oidc-provider/token.actions.githubusercontent.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - repo:yuyacode/AppLiftCommonInfra:*
                  - repo:yuyacode/AppLift:*
                  - repo:yuyacode/AppLiftMessageApi:*
                  - repo:yuyacode/AppLiftMessageScheduler:*
      ManagedPolicyArns:
        - !Ref CloudFormationStackManagementPolicy
      Policies:
        - PolicyName: "IamRoleManagementPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:UpdateRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:UpdateAssumeRolePolicy
                Resource: "*"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "This IAM role is used by GitHub Actions to deploy CloudFormation templates that dynamically create, update, and delete various IAM roles. Restricting the resource ARNs is not feasible due to the nature of the automation."
          - id: W28
            reason: "Fixed role name is required so that GitHub Actions can reliably assume this IAM role using its ARN."

Outputs:
  CloudFormationStackManagementPolicyArn:
    Description: ARN of the CloudFormation Stack Management Policy
    Value: !Ref CloudFormationStackManagementPolicy
    Export:
      Name: !Sub "${AWS::StackName}-CloudFormationStackManagementPolicyArn"
  IamRoleStackDeploymentRoleArn:
    Description: "ARN of the role used to deploy IAM roles via CloudFormation with full IAM permissions"
    Value: !GetAtt IamRoleStackDeploymentRole.Arn
