AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template defines shared network infrastructure resources, such as VPCs, subnets, and ALBs, that are commonly used across multiple components of a single application.
  Each component may be developed and deployed independently using different technologies, but they all rely on this foundational network layer.
  These resources are intentionally designed to be independent from any single component or technology, serving as a common infrastructure for the application's overall architecture.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W60
            reason: "Currently, the service has minimal usage, and the cost of maintaining VPC Flow Logs outweighs the benefits. We plan to enable Flow Logs in the future as the service scales and security requirements grow."
  PublicSubnet1a:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: "10.10.1.0/24"
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
  PrivateSubnet1a:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: "10.10.2.0/24"
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
  PublicSubnet1c:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: "10.10.3.0/24"
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
  PrivateSubnet1c:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: "10.10.4.0/24"
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC

Outputs:
  VPCId:
    Description: The ID of the VPC
    Value: !Ref VPC
