name: cfn-lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Add cfn-lint problem matcher
        run: echo "::add-matcher::.github/cfn-lint.json"

      - name: Run cfn-lint
        run: |
          files="gha-oidc-provisioner-role-setup.yaml"
          for file in $files; do
            cfn-lint "$file" -f parseable
          done
