name: Create IAM Role for deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'iam_role_for_deploy.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  create_iam_role_for_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_STACK_DEPLOYMENT_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Create IAM Role For Deployment
        run: |
          aws cloudformation deploy \
            --template-file iam_role_for_deploy.yaml \
            --stack-name IAM-Role-For-Deployment
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
            --parameter-overrides GitHubOIDCProviderArn=${{ secrets.GH_OIDC_PROVIDER_ARN }}
